import React, { useState } from 'react';
import Icon from '../../../components/AppIcon';
import Button from '../../../components/ui/Button';
import Input from '../../../components/ui/Input';

const IntegrationSetup = ({ integrations, onIntegrationToggle, onIntegrationUpdate }) => {
  const [showQRCode, setShowQRCode] = useState(false);
  const [showEmbedCode, setShowEmbedCode] = useState(false);
  const [copiedItem, setCopiedItem] = useState(null);

  const integrationOptions = [
    {
      id: 'whatsapp',
      name: 'WhatsApp Business',
      description: 'Connect your WhatsApp Business account for direct messaging',
      icon: 'MessageCircle',
      color: 'bg-success/10 text-success',
      features: ['Direct messaging', 'Media sharing', 'Quick replies', 'Business profile'],
      setupRequired: true,
      qrCode: true
    },
    {
      id: 'instagram',
      name: 'Instagram DM',
      description: 'Respond to Instagram direct messages automatically',
      icon: 'Instagram',
      color: 'bg-accent/10 text-accent',
      features: ['DM automation', 'Story replies', 'Comment responses', 'Media handling'],
      setupRequired: true,
      qrCode: false
    },
    {
      id: 'website',
      name: 'Website Chat Widget',
      description: 'Embed a chat widget on your website for instant customer support',
      icon: 'Globe',
      color: 'bg-secondary/10 text-secondary',
      features: ['Customizable design', 'Mobile responsive', 'Lead capture', 'File sharing'],
      setupRequired: false,
      qrCode: false,
      embedCode: true
    }
  ];

  const handleCopy = async (text, itemId) => {
    try {
      await navigator.clipboard?.writeText(text);
      setCopiedItem(itemId);
      setTimeout(() => setCopiedItem(null), 2000);
    } catch (err) {
      console.error('Failed to copy text: ', err);
    }
  };

  const generateQRCode = () => {
    // Mock QR code URL - in real app, this would be generated by backend
    return `https://api.qrserver.com/v1/create-qr-code/?size=200x200&data=https://wa.me/+1234567890?text=Hello%20I%20would%20like%20to%20connect%20with%20your%20business`;
  };

  const generateEmbedCode = () => {
    return `<!-- Rocket.new Chat Widget -->
<script>
  (function(w,d,s,o,f,js,fjs){
    w['RocketChat']=o;w[o]=w[o]||function(){(w[o].q=w[o].q||[]).push(arguments)};
    js=d.createElement(s),fjs=d.getElementsByTagName(s)[0];
    js.id=o;js.src=f;js.async=1;fjs.parentNode.insertBefore(js,fjs);
  }(window,document,'script','rocket','https://widget.rocket.new/v1/widget.js'));
  
  rocket('init', {
    agentId: 'your-agent-id-here',
    theme: 'light',
    position: 'bottom-right',
    primaryColor: '#00D1FF'
  });
</script>`;
  };

  return (
    <div className="space-y-8">
      <div className="text-center space-y-2">
        <h3 className="text-lg font-semibold text-foreground">Connect Your Channels</h3>
        <p className="text-muted-foreground">
          Choose how customers can reach your AI assistant
        </p>
      </div>
      {/* Integration Options */}
      <div className="space-y-6">
        {integrationOptions?.map((integration) => {
          const isEnabled = integrations?.[integration?.id]?.enabled || false;
          
          return (
            <div
              key={integration?.id}
              className={`
                border-2 rounded-xl p-6 transition-all duration-200
                ${isEnabled 
                  ? 'border-secondary bg-secondary/5' :'border-border bg-card'
                }
              `}
            >
              <div className="flex items-start justify-between mb-4">
                <div className="flex items-start space-x-4">
                  <div className={`
                    w-12 h-12 rounded-lg flex items-center justify-center flex-shrink-0
                    ${isEnabled ? integration?.color : 'bg-muted text-muted-foreground'}
                  `}>
                    <Icon name={integration?.icon} size={24} />
                  </div>
                  
                  <div className="flex-1">
                    <h4 className="text-lg font-semibold text-foreground mb-2">
                      {integration?.name}
                    </h4>
                    <p className="text-sm text-muted-foreground mb-4">
                      {integration?.description}
                    </p>
                    
                    <div className="flex flex-wrap gap-2">
                      {integration?.features?.map((feature, index) => (
                        <span
                          key={index}
                          className="inline-flex items-center px-2 py-1 rounded-md bg-muted text-muted-foreground text-xs font-medium"
                        >
                          {feature}
                        </span>
                      ))}
                    </div>
                  </div>
                </div>
                
                <div className="flex items-center space-x-2">
                  <button
                    onClick={() => onIntegrationToggle(integration?.id, !isEnabled)}
                    className={`
                      relative inline-flex h-6 w-11 items-center rounded-full transition-colors focus:outline-none focus:ring-2 focus:ring-ring focus:ring-offset-2
                      ${isEnabled ? 'bg-secondary' : 'bg-muted'}
                    `}
                  >
                    <span
                      className={`
                        inline-block h-4 w-4 transform rounded-full bg-white transition-transform
                        ${isEnabled ? 'translate-x-6' : 'translate-x-1'}
                      `}
                    />
                  </button>
                </div>
              </div>
              {/* Setup Options */}
              {isEnabled && (
                <div className="mt-6 pt-6 border-t border-border space-y-4">
                  {integration?.id === 'whatsapp' && (
                    <div className="space-y-4">
                      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                        <Input
                          label="WhatsApp Business Phone"
                          type="tel"
                          placeholder="+1 (555) 123-4567"
                          value={integrations?.whatsapp?.phone || ''}
                          onChange={(e) => onIntegrationUpdate('whatsapp', { phone: e?.target?.value })}
                        />
                        <Input
                          label="Business Display Name"
                          type="text"
                          placeholder="Your Business Name"
                          value={integrations?.whatsapp?.displayName || ''}
                          onChange={(e) => onIntegrationUpdate('whatsapp', { displayName: e?.target?.value })}
                        />
                      </div>
                      
                      <div className="flex items-center space-x-4">
                        <Button
                          variant="outline"
                          onClick={() => setShowQRCode(!showQRCode)}
                          iconName="QrCode"
                          iconPosition="left"
                        >
                          {showQRCode ? 'Hide QR Code' : 'Generate QR Code'}
                        </Button>
                        
                        {showQRCode && (
                          <div className="flex items-center space-x-4 p-4 bg-muted/50 rounded-lg">
                            <img
                              src={generateQRCode()}
                              alt="WhatsApp QR Code"
                              className="w-24 h-24 rounded-lg"
                            />
                            <div>
                              <p className="text-sm font-medium text-foreground mb-1">
                                WhatsApp Quick Connect
                              </p>
                              <p className="text-xs text-muted-foreground">
                                Customers can scan this QR code to start a conversation
                              </p>
                            </div>
                          </div>
                        )}
                      </div>
                    </div>
                  )}

                  {integration?.id === 'instagram' && (
                    <div className="space-y-4">
                      <Input
                        label="Instagram Username"
                        type="text"
                        placeholder="@yourbusiness"
                        value={integrations?.instagram?.username || ''}
                        onChange={(e) => onIntegrationUpdate('instagram', { username: e?.target?.value })}
                      />
                      
                      <div className="bg-warning/10 border border-warning/20 rounded-lg p-4">
                        <div className="flex items-start space-x-3">
                          <Icon name="AlertTriangle" size={20} className="text-warning flex-shrink-0 mt-0.5" />
                          <div>
                            <p className="text-sm font-medium text-foreground mb-1">
                              Instagram Business Account Required
                            </p>
                            <p className="text-xs text-muted-foreground">
                              You'll need to connect your Instagram Business account through Facebook Business Manager to enable DM automation.
                            </p>
                          </div>
                        </div>
                      </div>
                    </div>
                  )}

                  {integration?.id === 'website' && (
                    <div className="space-y-4">
                      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                        <Input
                          label="Widget Position"
                          type="text"
                          value="Bottom Right"
                          disabled
                        />
                        <Input
                          label="Primary Color"
                          type="color"
                          value={integrations?.website?.primaryColor || '#00D1FF'}
                          onChange={(e) => onIntegrationUpdate('website', { primaryColor: e?.target?.value })}
                        />
                      </div>
                      
                      <div className="space-y-2">
                        <Button
                          variant="outline"
                          onClick={() => setShowEmbedCode(!showEmbedCode)}
                          iconName="Code"
                          iconPosition="left"
                        >
                          {showEmbedCode ? 'Hide Embed Code' : 'Show Embed Code'}
                        </Button>
                        
                        {showEmbedCode && (
                          <div className="bg-muted/50 rounded-lg p-4">
                            <div className="flex items-center justify-between mb-2">
                              <p className="text-sm font-medium text-foreground">
                                Website Embed Code
                              </p>
                              <Button
                                variant="ghost"
                                size="sm"
                                onClick={() => handleCopy(generateEmbedCode(), 'embed')}
                                iconName={copiedItem === 'embed' ? "Check" : "Copy"}
                                iconPosition="left"
                              >
                                {copiedItem === 'embed' ? 'Copied!' : 'Copy'}
                              </Button>
                            </div>
                            <pre className="text-xs text-muted-foreground bg-card border border-border rounded p-3 overflow-x-auto">
                              {generateEmbedCode()}
                            </pre>
                            <p className="text-xs text-muted-foreground mt-2">
                              Paste this code before the closing &lt;/body&gt; tag on your website
                            </p>
                          </div>
                        )}
                      </div>
                    </div>
                  )}
                </div>
              )}
            </div>
          );
        })}
      </div>
      {/* Integration Summary */}
      <div className="bg-card border border-border rounded-xl p-6">
        <h4 className="text-lg font-semibold text-foreground mb-4">Integration Summary</h4>
        
        <div className="space-y-3">
          {integrationOptions?.map((integration) => {
            const isEnabled = integrations?.[integration?.id]?.enabled || false;
            
            return (
              <div key={integration?.id} className="flex items-center justify-between py-2">
                <div className="flex items-center space-x-3">
                  <div className={`
                    w-8 h-8 rounded-lg flex items-center justify-center
                    ${isEnabled ? integration?.color : 'bg-muted text-muted-foreground'}
                  `}>
                    <Icon name={integration?.icon} size={16} />
                  </div>
                  <span className="text-sm font-medium text-foreground">
                    {integration?.name}
                  </span>
                </div>
                <div className="flex items-center space-x-2">
                  {isEnabled ? (
                    <>
                      <Icon name="Check" size={16} className="text-success" />
                      <span className="text-sm text-success font-medium">Connected</span>
                    </>
                  ) : (
                    <>
                      <Icon name="X" size={16} className="text-muted-foreground" />
                      <span className="text-sm text-muted-foreground">Not connected</span>
                    </>
                  )}
                </div>
              </div>
            );
          })}
        </div>
      </div>
    </div>
  );
};

export default IntegrationSetup;